### ISSUE TITLE
ПР4 (ломаная линия)

### ISSUE THREAD

**Issue by drxaos** [Adgam/Java#1]
1. toStringCoordinatesPoints и toStringCoordinates - в джаве обычно для перевода объекта в строку служит метод toString. Если код перевода не делает ничего "тяжелого" (типа обращения к файлам или к бд), то лучше переопределить им toString().
2. Аналогично вместо comparePoints лучше переопределить стандартный equals().
3. Метод BrokenLine.searchVertexs() занимается не своим делом - выводит информацию на экран. Логичнее, если это будет делать Interface.

**Comment by Adgam** [comment]
1. fixed 0cec66d
2. fixed 809b418
3. fixed 360f2c5

**Comment by drxaos** [comment]
Имеется в виду стандартный метод класса Object:
```
    public boolean equals(Object obj) {
        // сравнение объектов
    }
```

**Comment by Adgam** [comment]
fixed 2a7ef2e
